/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogodavelha;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author Rafael
 */
public class TelaJogo extends javax.swing.JFrame {

    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        Reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(470, 470));

        jToggleButton1.setBackground(new java.awt.Color(51, 255, 51));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setBackground(new java.awt.Color(51, 255, 51));
        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setBackground(new java.awt.Color(51, 255, 51));
        jToggleButton3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setBackground(new java.awt.Color(51, 255, 51));
        jToggleButton4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jToggleButton4.setForeground(new java.awt.Color(60, 63, 65));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton5.setBackground(new java.awt.Color(51, 255, 51));
        jToggleButton5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton6.setBackground(new java.awt.Color(51, 255, 51));
        jToggleButton6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToggleButton7.setBackground(new java.awt.Color(51, 255, 51));
        jToggleButton7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        jToggleButton8.setBackground(new java.awt.Color(51, 255, 51));
        jToggleButton8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        jToggleButton9.setBackground(new java.awt.Color(51, 255, 51));
        jToggleButton9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        Reset.setText("RECOMEÇAR");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Reset, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        logicaJogo(jToggleButton8);
        verificarGanhador();
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        logicaJogo(jToggleButton3);
        verificarGanhador();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
       logicaJogo(jToggleButton4);
       verificarGanhador();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       logicaJogo(jToggleButton1);
       verificarGanhador();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        logicaJogo(jToggleButton2);
        verificarGanhador();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        logicaJogo(jToggleButton9);
        verificarGanhador();
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        logicaJogo(jToggleButton7);
        verificarGanhador();
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        logicaJogo(jToggleButton6);
        verificarGanhador();
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        logicaJogo(jToggleButton5);
        verificarGanhador();
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        limpar();
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }
    public int auxiliar = 1;
    
      
    public void logicaJogo(JToggleButton botao){
        
        
        if(auxiliar%2 == 0){
            botao.setText("X");
            botao.setBackground(Color.pink);
            auxiliar ++;
           if(botao.getText() == "O"){
              botao.setText("O");
              botao.setBackground(Color.cyan); 
           }

        }
        else{
            botao.setText("O");
            botao.setBackground(Color.cyan);
            auxiliar ++;
             if(botao.getText() == "X"){
              botao.setText("X");
              botao.setBackground(Color.pink); 
           }
        }
        
    }
    public void limpar(){
        jToggleButton1.setBackground(Color.GREEN);
        jToggleButton2.setBackground(Color.GREEN);
        jToggleButton3.setBackground(Color.GREEN);
        jToggleButton4.setBackground(Color.GREEN);
        jToggleButton5.setBackground(Color.GREEN);
        jToggleButton6.setBackground(Color.GREEN);
        jToggleButton7.setBackground(Color.GREEN);
        jToggleButton8.setBackground(Color.GREEN);
        jToggleButton9.setBackground(Color.GREEN);
        
        jToggleButton1.setText("");
        jToggleButton2.setText("");
        jToggleButton3.setText("");
        jToggleButton4.setText("");
        jToggleButton5.setText("");
        jToggleButton6.setText("");
        jToggleButton7.setText("");
        jToggleButton8.setText("");
        jToggleButton9.setText("");
    }
    
    public void verificarGanhador(){
        if(jToggleButton4.getText()== "X" & jToggleButton3.getText()== "X" & jToggleButton1.getText()== "X"){
              JOptionPane.showMessageDialog(null,"JOGADOR 2 GANHOU");
              limpar();
        }
        else if(jToggleButton2.getText()== "X" & jToggleButton8.getText()== "X" & jToggleButton9.getText()== "X"){
             JOptionPane.showMessageDialog(null,"JOGADOR 2 GANHOU");
             limpar();
        }
        else if(jToggleButton7.getText()== "X" & jToggleButton6.getText()== "X" & jToggleButton5.getText()== "X"){
             JOptionPane.showMessageDialog(null,"JOGADOR 2 GANHOU");
             limpar();
        }
        else if(jToggleButton4.getText()== "X" & jToggleButton8.getText()== "X" & jToggleButton5.getText()== "X"){
             JOptionPane.showMessageDialog(null,"JOGADOR 2 GANHOU");
             limpar();
        }
        else if(jToggleButton7.getText()== "X" & jToggleButton8.getText()== "X" & jToggleButton1.getText()== "X"){
             JOptionPane.showMessageDialog(null,"JOGADOR 2 GANHOU");
             limpar();
        }
        else if(jToggleButton4.getText()== "X" & jToggleButton2.getText()== "X" & jToggleButton7.getText()== "X"){
             JOptionPane.showMessageDialog(null,"JOGADOR 2 GANHOU");
             limpar();
        }
        else if(jToggleButton3.getText()== "X" & jToggleButton8.getText()== "X" & jToggleButton6.getText()== "X"){
             JOptionPane.showMessageDialog(null,"JOGADOR 2 GANHOU");
             limpar();
        }
        else if(jToggleButton1.getText()== "X" & jToggleButton9.getText()== "X" & jToggleButton5.getText()== "X"){
             JOptionPane.showMessageDialog(null,"JOGADOR 2 GANHOU");
             limpar();
        }
        
        
        
        
        
        
        else if(jToggleButton4.getText()== "O" & jToggleButton3.getText()== "O" & jToggleButton1.getText()== "O"){
             JOptionPane.showMessageDialog(null,"JOGADOR 1 GANHOU");
             limpar();
        }
        else if(jToggleButton2.getText()== "O" & jToggleButton8.getText()== "O" & jToggleButton9.getText()== "O"){
             JOptionPane.showMessageDialog(null,"JOGADOR 1 GANHOU");
             limpar();
        }
        else if(jToggleButton7.getText()== "O" & jToggleButton6.getText()== "O" & jToggleButton5.getText()== "O"){
             JOptionPane.showMessageDialog(null,"JOGADOR 1 GANHOU");
             limpar();
        }
        else if(jToggleButton4.getText()== "O" & jToggleButton8.getText()== "O" & jToggleButton5.getText()== "O"){
             JOptionPane.showMessageDialog(null,"JOGADOR 1 GANHOU");
             limpar();
        }
        else if(jToggleButton7.getText()== "O" & jToggleButton8.getText()== "O" & jToggleButton1.getText()== "O"){
             JOptionPane.showMessageDialog(null,"JOGADOR 1 GANHOU");
             limpar();
        }
        else if(jToggleButton4.getText()== "O" & jToggleButton2.getText()== "O" & jToggleButton7.getText()== "O"){
             JOptionPane.showMessageDialog(null,"JOGADOR 1 GANHOU");
             limpar();
        }
        else if(jToggleButton3.getText()== "O" & jToggleButton8.getText()== "O" & jToggleButton6.getText()== "O"){
             JOptionPane.showMessageDialog(null,"JOGADOR 1 GANHOU");
             limpar();
        }
        else if(jToggleButton1.getText()== "O" & jToggleButton9.getText()== "O" & jToggleButton5.getText()== "O"){
             JOptionPane.showMessageDialog(null,"JOGADOR 1 GANHOU");
             limpar();
        }
       

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
